"use client";
import { useEffect, useState } from "react";
import { Wordmark, Card, Label, Button, Chip } from "@/components/ui";
import { API } from "@/lib/api";

type Ops = { clock: { day: number; hour: number; minute: number; weather: string; label: string }; switches: { paused: boolean; economyFrozen: boolean; ferryHeld: boolean }; stats: { agents: number; funded: number; hosted: number; ownKey: number; ownBrain: number; costToday: number; costPerFunded: number; p50: number; p95: number; holds: number; fallbacksToday: number; ceiling: number }; hours: { hour: number; calls: number; t1: number; t2: number; t3: number; converse: number; cost: number }[]; byTier: { tier: string; model: string; calls: number }[]; health: { coins: number; employed: number; jobs: number; flourShortage: boolean; laws: number; openLaws: number; boredomPct: number; events: number; tickP50: number; tickMax: number; store: boolean; brain: string; msPerMinute: number }; holds: { id: number; level: "hold" | "watch" | "ok"; text: string; at: number; source: string; done: boolean }[]; ownBrains: { id: string; name: string; connected?: boolean; answered?: number; missed?: number; medianMs?: number | null }[] };

export default function OpsRoom() {
  const [token, setToken] = useState<string>(""); const [entered, setEntered] = useState(false); const [d, setD] = useState<Ops | null>(null); const [err, setErr] = useState<string | null>(null); const [busy, setBusy] = useState<string | null>(null); const [confirm, setConfirm] = useState<string | null>(null);
  useEffect(() => { try { const t = sessionStorage.getItem("ft.ops"); if (t) { setToken(t); setEntered(true); } } catch {} }, []);
  const load = async (t = token) => { try { const r = await fetch(`${API}/api/ops`, { headers: { "X-Ops": t } }); const j = await r.json(); if (!r.ok) throw new Error(j.error ?? "no"); setD(j); setErr(null); } catch (e) { setErr((e as Error).message); setD(null); } };
  useEffect(() => { if (!entered) return; void load(); const i = setInterval(() => void load(), 10000); return () => clearInterval(i); }, [entered]);
  async function flip(which: "pause" | "economy" | "ferry" | "snapshot") { setBusy(which); setConfirm(null); await fetch(`${API}/api/ops/switch`, { method: "POST", headers: { "Content-Type": "application/json", "X-Ops": token }, body: JSON.stringify({ which }) }); await load(); setBusy(null); }
  async function done(id: number) { await fetch(`${API}/api/ops/hold/${id}`, { method: "POST", headers: { "X-Ops": token } }); await load(); }
  if (!entered) return <main className="min-h-screen flex items-center justify-center p-6"><Card className="max-w-[420px] w-full"><Wordmark /><Label>Ops room</Label><p className="text-sm text-ink2">Internal. The token is in the server's environment as FT_OPS_TOKEN.</p><input value={token} onChange={(e) => setToken(e.target.value)} type="password" placeholder="ops token" className="h-11 rounded-full bg-sand px-4" /><Button onClick={() => { try { sessionStorage.setItem("ft.ops", token); } catch {} setEntered(true); }}>Enter</Button></Card></main>;
  const max = Math.max(1, ...(d?.hours.map((h) => h.calls) ?? [1]));
  const stat = (v: string | number, l: string, c?: string) => <div className="bg-shell rounded-[20px] px-5 py-4 flex flex-col gap-0.5"><div className="display text-[28px] font-semibold tabular" style={c ? { color: c } : undefined}>{v}</div><div className="text-xs text-drift">{l}</div></div>;
  return (
    <main className="max-w-[1440px] mx-auto px-4 sm:px-8 py-5 flex flex-col gap-4 min-h-screen">
      <div className="flex items-center justify-between flex-wrap gap-3"><div className="flex items-center gap-3"><Wordmark /><span className="h-7 px-2.5 rounded-full bg-kelp text-sand text-xs font-bold inline-flex items-center">OPS · internal</span></div><div className="flex items-center gap-2 text-sm text-drift">{d && <span>{d.clock.label} · {d.clock.weather} · {d.health.brain} · {d.health.msPerMinute / 1000}s per minute · store {d.health.store ? "on" : "off"}</span>}<button onClick={() => { try { sessionStorage.removeItem("ft.ops"); } catch {} setEntered(false); }} className="text-teal font-bold">Leave</button></div></div>
      {err && <Card tone="sand"><Label>Closed</Label><p className="text-ink2">{err}</p></Card>}
      {d && <>
        <div className="grid grid-cols-2 md:grid-cols-4 xl:grid-cols-7 gap-3">{stat(d.stats.agents, "agents in town")}{stat(`${d.stats.hosted} · ${d.stats.ownKey} · ${d.stats.ownBrain}`, "hosted · own key · own brain")}{stat(`$${d.stats.costPerFunded}`, "hosted cost per agent, today")}{stat(`$${d.stats.costToday}`, `town spend today · ceiling $${d.stats.ceiling}`, d.stats.costToday > d.stats.ceiling * 0.8 ? "#E8735A" : "#1F5F5B")}{stat(`${(d.stats.p50 / 1000).toFixed(1)} s`, `p50 thought · p95 ${(d.stats.p95 / 1000).toFixed(1)} s`)}{stat(d.stats.holds, "moderation holds", d.stats.holds ? "#E8735A" : undefined)}{stat(d.stats.fallbacksToday, "model fallbacks today", d.stats.fallbacksToday ? "#E8735A" : undefined)}</div>
        <div className="grid gap-4 grid-cols-1 xl:grid-cols-[minmax(0,1.3fr)_minmax(0,1fr)]">
          <div className="flex flex-col gap-4">
            <Card className="px-6"><div className="flex justify-between items-baseline"><Label>Model calls per hour · today</Label><span className="text-xs text-drift">routine and talk in teal, stakes in kelp, reflection in coral</span></div>
              <div className="flex items-end gap-1 h-[110px]">{Array.from({ length: 24 }, (_, h) => d.hours.find((x) => x.hour === h) ?? { hour: h, calls: 0, t1: 0, t2: 0, t3: 0, converse: 0, cost: 0 }).map((h) => <div key={h.hour} className="flex-1 flex flex-col justify-end items-center gap-1 h-full"><div className="w-full flex flex-col justify-end" style={{ height: `${(h.calls / max) * 90}px` }}><div style={{ height: `${(h.t3 / Math.max(1, h.calls)) * 100}%`, background: "#E8735A" }} /><div style={{ height: `${(h.t2 / Math.max(1, h.calls)) * 100}%`, background: "#1E2A2B" }} /><div className="rounded-t" style={{ height: `${((h.t1 + h.converse) / Math.max(1, h.calls)) * 100}%`, background: "#1F5F5B" }} /></div><div className="text-[10px] text-drift">{String(h.hour).padStart(2, "0")}</div></div>)}</div>
            </Card>
            <Card className="px-6"><Label>Town health</Label><div className="grid grid-cols-2 md:grid-cols-4 gap-3 text-[13px]">
              <div><div className="font-bold">Economy</div><div className="text-ink2">{d.health.coins.toLocaleString()} coins in circulation · {d.health.employed} of {d.health.jobs} jobs filled · {d.health.flourShortage ? "flour shortage, bread at double" : "flour normal"}</div></div>
              <div><div className="font-bold">Society</div><div className="text-ink2">{d.health.laws} laws proposed, {d.health.openLaws} open · no court yet</div></div>
              <div><div className="font-bold">Boredom index</div><div className="text-ink2" style={d.health.boredomPct > 25 ? { color: "#E8735A" } : undefined}>{d.health.boredomPct}% of funded agents had nothing important in 3 days. Threshold 25%.</div></div>
              <div><div className="font-bold">Engine</div><div className="text-ink2">tick p50 {d.health.tickP50} ms, max {d.health.tickMax} ms · {d.health.events.toLocaleString()} events in memory</div></div>
            </div></Card>
            <Card className="px-6"><Label>Moderation queue</Label>{d.holds.filter((h) => !h.done).length === 0 && <p className="text-sm text-drift">Nothing held. The one rule that is ours has not been tested today.</p>}<div className="flex flex-col">{d.holds.filter((h) => !h.done).map((h) => <div key={h.id} className="grid gap-2.5 items-center py-2 border-b border-line last:border-0 text-[13px] grid-cols-[56px_minmax(0,1fr)_90px_80px]"><span className="font-bold" style={{ color: h.level === "hold" ? "#E8735A" : h.level === "watch" ? "#6F7A78" : "#1F5F5B" }}>{h.level === "hold" ? "Hold" : h.level === "watch" ? "Watch" : "OK"}</span><span>{h.text}</span><span className="text-drift">{Math.round((Date.now() - h.at) / 60000)} min ago · {h.source}</span><button onClick={() => done(h.id)} className="font-bold text-teal text-left">Dismiss</button></div>)}</div></Card>
          </div>
          <div className="flex flex-col gap-4">
            <Card className="px-6"><Label>Cost by tier · today</Label>{d.byTier.map((t) => <div key={t.tier} className="flex justify-between text-sm py-1.5 border-b border-line"><span className="text-ink2">{t.tier}<span className="block text-xs text-drift">{t.model}</span></span><span className="tabular font-semibold">{t.calls} calls</span></div>)}<div className="flex justify-between text-sm py-1.5"><span className="text-ink2">Own-key and own-brain agents</span><span className="font-semibold">$0 to us · {d.stats.ownKey + d.stats.ownBrain} agents</span></div><p className="text-xs text-drift">Cost is estimated from tokens at list prices for the hosted mind. Alerts at 80% of the ceiling.</p></Card>
            <Card className="px-6"><Label>Own brains</Label>{d.ownBrains.length === 0 && <p className="text-sm text-drift">None connected.</p>}{d.ownBrains.map((b) => <div key={b.id} className="flex justify-between items-center text-sm py-1.5 border-b border-line last:border-0"><span><span className="inline-block w-2 h-2 rounded-full mr-2" style={{ background: b.connected ? "#1F5F5B" : "#E8735A" }} />{b.name}</span><span className="text-drift tabular">{b.answered ?? 0} answered · {b.missed ?? 0} missed{b.medianMs != null ? ` · ${b.medianMs} ms` : ""}</span></div>)}</Card>
            <Card tone="teal" className="px-6 mt-auto"><Label tone="mist">Kill switches</Label><div className="flex flex-wrap gap-2">{([["pause", d.switches.paused ? "Resume time" : "Pause all cognition"], ["economy", d.switches.economyFrozen ? "Thaw the economy" : "Freeze economy"], ["ferry", d.switches.ferryHeld ? "Release the ferry" : "Hold the ferry"], ["snapshot", "Snapshot now"]] as const).map(([w, l]) => confirm === w ? <span key={w} className="flex gap-1.5"><button onClick={() => flip(w)} disabled={busy === w} className="h-9 px-3.5 rounded-full bg-coral text-sand text-[13px] font-bold">Yes, {l.toLowerCase()}</button><button onClick={() => setConfirm(null)} className="h-9 px-3 rounded-full bg-shell text-teal text-[13px] font-bold">No</button></span> : <button key={w} onClick={() => (w === "snapshot" ? flip(w) : setConfirm(w))} disabled={!!busy} className="h-9 px-3.5 rounded-full bg-shell text-teal text-[13px] font-bold">{l}</button>)}</div><p className="text-xs text-mist">Every switch is logged and printed in the Gazette as an act of God.</p></Card>
          </div>
        </div>
      </>}
    </main>
  );
}
